/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Litre_Cascara.gltf
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from "@react-three/fiber";

export function Cascara(props) {
  const group = useRef();
  useFrame(() => (group.current.rotation.y += 0.01));

  const { nodes, materials } = useGLTF('/models/cascara/Litre_Cascara.gltf')
  return (
    <group {...props} dispose={null}>
      <group ref={group} position={[0, -15, -35]}>
        <mesh geometry={nodes.Bottle_litre_Wine_1.geometry} material={materials['1001']} />
        <mesh geometry={nodes.Bottle_litre_Wine_2.geometry} material={materials['1001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cascara/Litre_Cascara.gltf')
